Get and List mandates
TrueLayer/truelayer-dotnet pull request #179
Opened 2023-08-02 14:17 UTC by mohammedmiah99

2023-08-02 14:19 UTC, mohammedmiah99 commented
Tests pass locally
![image](https://github.com/TrueLayer/truelayer-dotnet/assets/63966452/12c33baa-86a6-4db3-bdfb-e00b8ab29a1f)
as well as build on fork:
https://github.com/1ststop/truelayer-dotnet/actions/runs/5738131490

2023-08-08 13:57 UTC, Couper4 requested changes

2023-08-08 13:57 UTC, Couper4 commented on src/TrueLayer/Mandates/IMandatesApi.cs
> +    using MandateDetailUnion = OneOf<Model.MandateDetail.AuthorizationRequiredMandateDetail, Model.MandateDetail.AuthorizingMandateDetail, Model.MandateDetail.AuthorizedMandateDetail, Model.MandateDe
```suggestion
    using MandateDetailUnion = OneOf<
      Model.MandateDetail.AuthorizationRequiredMandateDetail,
      Model.MandateDetail.AuthorizingMandateDetail,
      Model.MandateDetail.AuthorizedMandateDetail,
      Model.MandateDetail.FailedMandateDetail,
      Model.MandateDetail.RevokedMandateDetail>;
```

2023-08-08 13:57 UTC, Couper4 commented on src/TrueLayer/Mandates/MandatesApi.cs
> +    using MandateDetailUnion = OneOf<Model.MandateDetail.AuthorizationRequiredMandateDetail, Model.MandateDetail.AuthorizingMandateDetail, Model.MandateDetail.AuthorizedMandateDetail, Model.MandateDe
```suggestion
    using MandateDetailUnion = OneOf<
      Model.MandateDetail.AuthorizationRequiredMandateDetail,
      Model.MandateDetail.AuthorizingMandateDetail,
      Model.MandateDetail.AuthorizedMandateDetail,
      Model.MandateDetail.FailedMandateDetail,
      Model.MandateDetail.RevokedMandateDetail>;
```

2023-08-08 13:57 UTC, Couper4 commented on src/TrueLayer/Mandates/MandatesApi.cs
> +                new Uri(_baseUri, $"/v3/mandates/{mandateId}"),
I think the resulting URI will be incorrect, it should be just `new Uri(_baseUri, "mandateId)`.


Having a look at how the [GetPayment method](https://github.com/1ststop/truelayer-dotnet/blob/dfc49f824b29d0bceb80c4fec43977ad70a541ab/src/TrueLayer/Payments/PaymentsApi.cs#L88) works might help here ;)

2023-08-08 13:57 UTC, Couper4 commented on src/TrueLayer/Mandates/MandatesApi.cs
> +            queryParameters["client_id"] = _options.ClientId;
Why `client_id` is here?

I don't see it [mentioned in the docs](https://docs.truelayer.com/reference/list-mandate).

2023-08-09 07:45 UTC, Couper4 requested changes
I've left some last minor comments.

Can you please also merge the main branch into this one?

Other than that LGTM 👍

2023-08-09 07:45 UTC, Couper4 commented on test/TrueLayer.AcceptanceTests/MandatesTests.cs
> +            createResponse.StatusCode.ShouldBe(HttpStatusCode.Created);
```suggestion
            // Arrange
            var createResponse = await _fixture.Client.Mandates.CreateMandate(
                mandateRequest, idempotencyKey: Guid.NewGuid().ToString());
            createResponse.StatusCode.ShouldBe(HttpStatusCode.Created);
            var mandateId = createResponse.Data!.Id;
            
            // Act
            var response = await _fixture.Client.Mandates.GetMandate(mandateId, MandateType.Sweeping);

            // Assert
            response.StatusCode.ShouldBe(HttpStatusCode.OK);
            response.Data.AsT0.User!.Id.ShouldBe(createResponse.Data.User!.Id);
```

2023-08-09 07:45 UTC, Couper4 commented on test/TrueLayer.AcceptanceTests/MandatesTests.cs
> +            createResponse.StatusCode.ShouldBe(HttpStatusCode.Created);
```suggestion
            // Arrange
            var createResponse = await _fixture.Client.Mandates.CreateMandate(
                mandateRequest, idempotencyKey: Guid.NewGuid().ToString());
            createResponse.StatusCode.ShouldBe(HttpStatusCode.Created);
            
            // Act
            var response = await _fixture.Client.Mandates.ListMandates(new ListMandatesQuery(createResponse.Data!.User.Id, null, 10), MandateType.Sweeping);

            // Assert
            response.StatusCode.ShouldBe(HttpStatusCode.OK);
            response.Data!.Items.Count().ShouldBeLessThanOrEqualTo(10);
```

2023-08-09 12:54 UTC, Couper4 approved these changes

2023-08-09 14:16 UTC, antoniovalentini approved these changes

2023-08-09 14:16 UTC, tl-antonio-valentini approved these changes

2023-08-10 07:33 UTC, tl-antonio-valentini commented
Builds seem to fail due to some secrets not being injected. They agreed with Mauro that if the unit tests pass it should be fine to merge.

2023-08-10 07:34 UTC, merged